const pageNames=["home","projects","award","history","contact"],panels=[...document.querySelectorAll("[data-page-panel]")],links=[...document.querySelectorAll(".page-link")],cards=[...document.querySelectorAll(".stack-card")],stackNav=document.querySelector(".stack-nav");
let current=pageNames.includes(location.hash.slice(1))?location.hash.slice(1):"home",busy=false,wheelTimer=0;
function updateStack(){const activeIndex=pageNames.indexOf(current);cards.forEach((card,index)=>{const offset=index-activeIndex,depth=Math.abs(offset);card.style.setProperty("--offset",offset);card.style.setProperty("--depth",depth);card.style.zIndex=10-depth;const active=index===activeIndex;card.classList.toggle("current",active);card.setAttribute("aria-pressed",String(active));card.tabIndex=active?0:-1});document.body.dataset.activePage=current}
function showPage(name){if(!pageNames.includes(name)||name===current||busy)return;busy=true;const old=document.querySelector(".page.active"),next=document.querySelector(`[data-page-panel="${name}"]`);old.classList.add("leaving");next.classList.add("preparing");next.setAttribute("aria-hidden","false");requestAnimationFrame(()=>requestAnimationFrame(()=>{old.classList.remove("active","leaving");old.setAttribute("aria-hidden","true");next.classList.remove("preparing");next.classList.add("active");current=name;updateStack();setTimeout(()=>busy=false,360)}))}
function navigate(name){if(!pageNames.includes(name)||busy)return;if(location.hash.slice(1)===name)showPage(name);else location.hash=name}
function step(direction){const index=pageNames.indexOf(current),next=Math.max(0,Math.min(pageNames.length-1,index+direction));if(next!==index)navigate(pageNames[next])}
links.forEach(link=>link.addEventListener("click",event=>{event.preventDefault();navigate(link.dataset.page)}));
addEventListener("hashchange",()=>showPage(location.hash.slice(1)||"home"));
stackNav.addEventListener("wheel",event=>{if(event.ctrlKey||Math.abs(event.deltaY)<8)return;event.preventDefault();if(busy||wheelTimer)return;wheelTimer=setTimeout(()=>wheelTimer=0,360);step(event.deltaY>0?1:-1)},{passive:false});
addEventListener("keydown",event=>{if(["ArrowDown","PageDown"].includes(event.key)){event.preventDefault();step(1)}if(["ArrowUp","PageUp"].includes(event.key)){event.preventDefault();step(-1)}});
panels.forEach(panel=>{const active=panel.dataset.pagePanel===current;panel.classList.toggle("active",active);panel.setAttribute("aria-hidden",String(!active))});updateStack();

const awardPage=document.querySelector(".award-page"),awardRows=[...document.querySelectorAll(".award-entry")],awardDetail=document.querySelector(".award-detail"),awardDetailBack=document.querySelector(".award-detail-back");
const awardDetailElements={visual:document.querySelector(".award-detail-visual"),image:document.querySelector("#award-detail-image"),caption:document.querySelector("#award-detail-caption"),kicker:document.querySelector("#award-detail-kicker"),title:document.querySelector("#award-detail-title"),lead:document.querySelector("#award-detail-lead"),project:document.querySelector("#award-detail-project"),approach:document.querySelector("#award-detail-approach"),result:document.querySelector("#award-detail-result"),link:document.querySelector("#award-detail-link")};
const awardDetails={
  hackathon:{image:"./assets/images/medical-ai-hackathon-2026.jpg",alt:"2026 강원대학교 의료 AI 해커톤 최우수상 수상 팀 기념사진",caption:"2026.07.29 · KANGWON NATIONAL UNIVERSITY",kicker:"2026 MEDICAL AI HACKATHON",title:'<span class="award-event-title">의료 AI 해커톤</span><br>최우수상 <span class="award-rank">1위</span>',lead:'대장내시경 용종 의심 영역을 실시간으로 분할하는 의료 컴퓨터 비전 프로젝트로 <strong>강원대학교 AI 부트캠프 의료 AI 해커톤</strong>에서 최우수상을 수상했습니다.',project:"실시간 대장내시경 용종 의심 영역 분할",approach:"SegFormer-B0 기반 Medical AI · Computer Vision",result:"2026 의료 AI 해커톤 최우수상 · 1위",href:"https://github.com/lucid7132",linkLabel:"GitHub 프로필 보기 ↗"},
  uni2:{image:"./assets/images/uni2-market-award-2026.jpg",alt:"2026 대한민국 학생창업주간 Uni 2 Market 최우수상 수상 사진",caption:"2026.07.09 · UNI 2 MARKET",kicker:"2026 KOREA STUDENT STARTUP WEEK",title:"Uni 2 Market<br>최우수상",lead:"IT대학 컴퓨터공학과 윤동건(석사 1년 차)과 박준영(학부연구생)이 2026년 7월 9일 교육부 주관 제3회 대한민국 학생창업주간의 Uni 2 Market에서 최우수상을 수상했습니다.",project:"제3회 2026 대한민국 학생창업주간 · Uni 2 Market",approach:"창업의 전 과정을 경험하는 몰입형 창업 훈련 프로그램",result:"전국 대학(원)생과 청소년 등 총 1,200명 참여 · 최우수상",href:"https://visual.kangwon.ac.kr/activity/award/%EC%88%98%EC%83%81-%EC%9C%A4%EB%8F%99%EA%B1%B4%EB%B0%95%EC%A4%80%EC%98%81-2026%EB%85%84%EB%8F%84-%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD-%ED%95%99%EC%83%9D%EC%B0%BD%EC%97%85%EC%A3%BC%EA%B0%84-%EC%B5%9C%EC%9A%B0%EC%88%98%EC%83%81-%EC%88%98%EC%83%81",linkLabel:"수상 소식 원문 보기 ↗",layout:"portrait"}
};
let lastAwardRow=null,detailCloseTimer=0;
function renderAwardDetail(key){const detail=awardDetails[key]||awardDetails.hackathon,hasImage=Boolean(detail.image);awardDetail.classList.toggle("no-image",!hasImage);awardDetail.classList.toggle("portrait-image",detail.layout==="portrait");awardDetailElements.visual.hidden=!hasImage;if(hasImage){awardDetailElements.image.src=detail.image;awardDetailElements.image.alt=detail.alt}awardDetailElements.caption.textContent=detail.caption;awardDetailElements.kicker.textContent=detail.kicker;awardDetailElements.title.innerHTML=detail.title;awardDetailElements.lead.innerHTML=detail.lead;awardDetailElements.project.textContent=detail.project;awardDetailElements.approach.textContent=detail.approach;awardDetailElements.result.textContent=detail.result;awardDetailElements.link.href=detail.href;awardDetailElements.link.textContent=detail.linkLabel;awardDetail.scrollTop=0}
function openAwardDetail(row){clearTimeout(detailCloseTimer);awardPage.classList.remove("detail-closing");lastAwardRow=row;renderAwardDetail(row.dataset.award||"hackathon");awardPage.classList.add("detail-open");awardDetail.setAttribute("aria-hidden","false");awardRows.forEach(item=>item.tabIndex=-1);requestAnimationFrame(()=>awardDetailBack.focus())}
function closeAwardDetail(restoreFocus=true){if(!awardPage.classList.contains("detail-open"))return;clearTimeout(detailCloseTimer);awardPage.classList.add("detail-closing");awardPage.classList.remove("detail-open");detailCloseTimer=setTimeout(()=>awardPage.classList.remove("detail-closing"),540);awardDetail.setAttribute("aria-hidden","true");awardRows.forEach(item=>item.tabIndex=0);if(restoreFocus&&lastAwardRow)lastAwardRow.focus()}
awardRows.forEach(row=>{row.tabIndex=0;row.setAttribute("role","button");row.setAttribute("aria-label","수상 상세 내용 보기");row.addEventListener("click",event=>{if(event.target.closest("a"))return;openAwardDetail(row)});row.addEventListener("keydown",event=>{if(["Enter"," "].includes(event.key)){event.preventDefault();openAwardDetail(row)}})});
awardDetailBack.addEventListener("click",()=>closeAwardDetail());
links.forEach(link=>link.addEventListener("click",()=>{if(link.dataset.page!=="award")closeAwardDetail(false)}));
addEventListener("keydown",event=>{if(event.key==="Escape"&&awardPage.classList.contains("detail-open")){event.preventDefault();closeAwardDetail()}});
